# Numpy - Exercícios

Gere uma matriz 5x5 utilizando *arrays* numpy, com o valor 2 na diagonal principal.

Saída:
```py
array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])
```

Gere uma matriz 10x10 utilizando *arrays* numpy, com o valor -1 na diagonal principal e 2 nas demais posições.

Saída:
```py
array([[1., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 1., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 1., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 1., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 1., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 1., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 1., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 1., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 1., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 1.]])
```

Gere uma matriz de ordem 7x7, com valores 0 na diagonal principal e 1 nas demais posições.

Saída:
```py
array([[0., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 0.]])
```

Para o próximo exercício, certifique-se que a biblioteca `names` esteja instalada e importada.

In [ ]:
!pip3 install names==0.3.0 >/dev/null 2>&1
import names

Utilize o código abaixo para gerar informações aleatórias, tendo:
- Sexo
- Nome
- Sobrenome
- Idade
- Peso

In [ ]:
seed = 42
n = 15
names.random.seed(seed)
np.random.seed(seed)
sexo = np.array(['male' if x else 'female' for x in np.random.randint(0,2,n)])
nomes = np.array([names.get_first_name(gender=g) for g in sexo])
sobrenomes = np.array([names.get_last_name() for _ in sexo])
idades = np.random.randint(10,60,n)
pesos = np.random.randint(30,120,n)
print('Sexo     :',sexo)
print('Nome     :',nomes)
print('Sobrenome:',sobrenomes)
print('Idade    :',idades)
print('Peso     :',pesos)

A partir dos dados gerados acima, responda:

- A idade média de todas as as pessoas
- O peso médio de todas as pessoas
- A altura média de todas as pessoas
- O peso médio das pessoas menores de 20 anos
- O peso médio das pessoas com idade entre 20 e 60 anos
- O peso médio das pessoas com mais de 60 anos
- O peso médio das pessoas, separadas por sexo
- A idade da pessoa mais alta, e da mais baixa
- A idade da pessoa com maior peso e da com menor peso
- A maior e menor idade, de acordo com cada sexo.

Crie um *array* numpy com valores aleatórios. Em seguida, mostre apenas os valores ímpares presentes no *array*.

Crie um *array* numpy com valores de 1 a 19. Em seguida, substitua todos os valores pares por -1.

Transforme os arrays
```
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
```
em um array de duas dimensões, concatenando-os verticalmente.

Saída:
```
array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])
```



In [ ]:
import names
import numpy as np

In [ ]:
names.get_first_name()

In [ ]:
seed = 42
n = 5
names.random.seed(seed)
np.random.seed(seed)
sexo = np.array(['male' if x else 'female' for x in np.random.randint(0,2,n)])
nomes = np.array([names.get_first_name(gender=g) for g in sexo])
sobrenomes = np.array([names.get_last_name() for _ in sexo])
idades = np.random.randint(10,60,n)
pesos = np.random.randint(30,120,n)
print('Sexo     :',sexo)
print('Nome     :',nomes)
print('Sobrenome:',sobrenomes)
print('Idade    :',idades)
print('Peso     :',pesos)