# Numpy - Exercícios

Gere uma matriz 5x5 utilizando *arrays* numpy, com o valor 2 na diagonal principal.

Saída:
```py
array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])
```

Gere uma matriz 10x10 utilizando *arrays* numpy, com o valor -1 na diagonal principal e 2 nas demais posições.

Saída:
```py
array([[1., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 1., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 1., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 1., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 1., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 1., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 1., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 1., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 1., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 1.]])
```

Gere uma matriz de ordem 7x7, com valores 0 na diagonal principal e 1 nas demais posições.

Saída:
```py
array([[0., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 0.]])
```

Gere *arrays* numpy com valores aleatórios, com `n` posições, de forma que `n` deve ser definido em uma variável.  
Os *arrays* gerados devem ser:
- idade: (valores entre 0 e 100 anos)
- peso:  (valores entre 1 e 120 kilos)
- altura (entre 0.5 e 2.0 metros)
- sexo   (f ou m)

Com base nos dados gerados, obtenha:
- A idade média de todas as as pessoas
- O peso médio de todas as pessoas
- A altura média de todas as pessoas
- O peso médio das pessoas menores de 20 anos
- O peso médio das pessoas com idade entre 20 e 60 anos
- O peso médio das pessoas com mais de 60 anos
- O peso médio das pessoas, separadas por sexo
- O IMC das pessoas, separadas por sexo
- A idade da pessoa mais alta, e da mais baixa
- A idade da pessoa com maior peso e da com menor peso
- A maior e menor idade, de acordo com cada sexo.

Crie um *array* numpy com valores aleatórios. Em seguida, mostre apenas os valores ímpares presentes no *array*.

Crie um *array* numpy com valores de 1 a 19. Em seguida, substitua todos os valores pares por -1.

Transforme os arrays
```
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
```
em um array de duas dimensões, concatenando-os verticalmente.

Saída:
```
array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])
```

