# Exercícios

Importe a biblioteca **numpy**, com o *alias* **np**.

Crie um *array* numpy de uma dimensão, com números de $0$ a $9$.

Saída:
```py
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Crie um *array* numpy de ordem 5x5 somente com valores `True`.

Saída:
```
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])
```

Crie um *array* com posições de 0 a 9, e transforme-o em um array com os valores organizados em duas colunas.

Saída:
```
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
```


Crie um array com posições de 0 a 9, e transforme-o em um array com os valores organizados em uma única coluna.

Saída:
```
array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])
```

Crie um *array* numpy com valores de 100 a 200, de forma que a diferença entre cada elemento seja 10.

Saída:
```
array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])
```

## Referências

[PRABHAKARAN, S. 101 NumPy Exercises for Data Analysis (Python). Machine Learning Plus, 2018.](https://www.machinelearningplus.com/python/101-numpy-exercises-python/)

[ROUGIER, N. P. 100 numpy exercises.](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)